### ISSUE TITLE
Staff Portal Log-in: Error page 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Aussie-Air#33]
**Log in page should follow the given design below**

![image](https://cloud.githubusercontent.com/assets/18568310/15697523/7b126baa-27ed-11e6-8479-d80e5fca0d03.png)

**Comment by ronadtitan** [comment]
its intentionally hidden.. only staff can acess

**Comment by ricatitan** [comment]
In my side as a QA, it was not mention in the scope that it will be intentionally hidden and only staff can access the reason why i reported it as a bug.
