### ISSUE TITLE
Ipad- News Listing: Contents must limit up to 5 lines only same in the desktop view

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Aussie-Air#40]
![image](https://cloud.githubusercontent.com/assets/18568310/15701581/b2cc8dda-280d-11e6-85f7-93e7c4eaada8.png)

**Comment by joancapuyan** [comment]
Does not need to follow 5 lines when in mobile as long as the content you see on desktop view, can also be seen on the ipad's view.
